apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend-deployment
  labels:
    app: demo-frontend
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        image: ghcr.io/octopussolutionsengineering/octopus-zero-to-hero/demo-frontend:2024.10.21.19 # Replace with your container image
        ports:
        - containerPort: 5002 # Port exposed by the container (matches the Dockerfile)
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-frontend-secret # Reference to the Secret object
              key: 

---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  labels:
    app: demo-frontend
spec:
  type: NodePort # Use NodePort for local access
  ports:
  - port: 80
    targetPort: 5002 # Port exposed by the container (matches the Dockerfile)
  selector:
    app: demo-frontend
