apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend-deployment
  labels:
    app: demo-frontend
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        image: ghcr.io/octopussolutionsengineering/octopus-zero-to-hero/demo-frontend:2024.10.21.19 # Replace with your container image
        ports:
        - containerPort: 5002 # Port exposed by the container (matches the Dockerfile)
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MY_SECRET # Refers to the key in the Kubernetes Secret
        - name: WELCOME_MESSAGE
          value: "Welcome to the Octopus Zero to Hero Webinar!" # Example environment variable
        - name: FOOTER_TEXT
          value: "Powered by Kubernetes and Octopus Deploy"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend-service
  labels:
    app: demo-frontend
spec:
  type: NodePort # Use NodePort for local access
  ports:
  - port: 80
    targetPort: 5002 # Port exposed by the container (matches the Dockerfile)
  selector:
    app: demo-frontend
